### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by romaniuk3** [romaniuk3/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Newpullg** [comment]
<h2>Resume</h2>

<p>On our way down to Castle Black. I drove a dagger into the walker's heart. I risked my own life to save more than once. I'm a greater warrior than either of you will ever be.</p>
