### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by romaniuk3** [romaniuk3/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Newpullg** [comment]
wiki: gameofthrones.fandom.com/wiki/Samwell_Tarly
facebook: https://www.facebook.com/GameOfThrones/
