### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by romaniuk3** [romaniuk3/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Newpullg** [comment]
Skills
Keen intellect, knowledge on various fields, Intuition, fast learner

Hobby
Studying and reading, eating, spending time with his friends

Goals
Become a master for the Night's Watch, survive winter and find new ways to fight the Others, convince the Enclave of the Citadel to warn the Seven Kingdoms about the threat of the Others, Protect Gilly
